name: Run Selenium Tests

on:
  push:
    branches:
      - main   # Tu peux remplacer par la branche que tu souhaites
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ hashFiles('/pom.xml') }}
          restore-keys: maven-

      - name: Run Maven tests
        run: mvn clean test